name: 守护之石
author: Phaed
main: net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones
version: ${project.version}
dev-url: http://dev.bukkit.org/server-mods/preciousstones/
load: 'postworld'
softdepend: [Permissions, PermissionsBukkit, SimpleClans, HawkEye, Vault, CombatTag, WorldGuard, LWC, Lockette, Spout, mcMMO, SCCore]
commands:
  ps:
    description: 所有守护之石的指令
    usage: 未确认命令
permissions:
  preciousstones.benefit.fields:
    description: 能使用 /ps fields 设置领域
  preciousstones.benefit.create.forcefield:
    description: 能创建力场领域
  preciousstones.benefit.create.unbreakable:
    description: 能创建守护领域
  preciousstones.benefit.disable:
    description: 能禁用拥有的领域
  preciousstones.benefit.enable:
    description: 能启用拥有的领域
  preciousstones.benefit.heal:
    description: 在治疗范围内能被治愈
  preciousstones.benefit.giveair:
    description: 在氧气范围内能得到氧气
  preciousstones.benefit.launch:
    description: 能设置发射
  preciousstones.benefit.bounce:
    description: 能设置弹跳
  preciousstones.benefit.setname:
    description: 能使用 /ps setname
  preciousstones.benefit.setradius:
    description: 能使用 /ps setradius
  preciousstones.benefit.setvelocity:
    description: 能使用 /ps setvelocity
  preciousstones.benefit.setinterval:
    description: 能使用 /ps setinterval
  preciousstones.benefit.mark:
    description: 能使用 /ps mark
  preciousstones.benefit.visualize:
    description: 能使用 /ps visualize
  preciousstones.benefit.who:
    description: 能使用 /ps who
  preciousstones.benefit.onoff:
    description: 能使用 /ps on and /ps off
  preciousstones.benefit.counts:
    description: 能使用 /ps counts
  preciousstones.benefit.locations:
    description: 能使用 /ps locations
  preciousstones.benefit.snitch:
    description: 能使用 /ps snitch list/clean
  preciousstones.benefit.feed:
    description: 可以得到饥饿度在食物方块
  preciousstones.benefit.potions:
    description: 可以加速在加速方块
  preciousstones.benefit.repair:
    description: 能通过材料修复
  preciousstones.benefit.toggle:
    description: 能使用 /ps toggle
  preciousstones.benefit.density:
    description: 能设置可视化密度
  preciousstones.benefit.change-owner:
    description: 可以更改领域的所有者
  preciousstones.benefit.hide:
    description: 可以控制领域是否隐藏
  preciousstones.benefit.setlimit:
    description: 可设置租赁限制
  preciousstones.admin.hideall:
    description: 可以控制全部领域是否隐藏
  preciousstones.whitelist.allow:
    description: 能使用 /ps allow (设置白名单)
  preciousstones.whitelist.allowed:
    description: 能使用 /ps allowed
  preciousstones.whitelist.allowall:
    description: 能使用 /ps allowall
  preciousstones.whitelist.remove:
    description: 能使用 /ps remove
  preciousstones.whitelist.removeall:
    description: 能使用 /ps removeall
  preciousstones.bypass.purchase:
    description: 可放置领域，而无需购买
  preciousstones.bypass.entry:
    description: 可以进入入门保护等领域
  preciousstones.bypass.pvp:
    description: 在PVP自由领域能够攻击玩家
  preciousstones.bypass.place:
    description: 可以放置方块在禁止放置区域
  preciousstones.bypass.use:
    description: 可以放置物品在禁止使用区域
  preciousstones.bypass.destroy:
    description: 可以破坏方块在禁止破坏区域
  preciousstones.bypass.protection:
    description: 可以破坏其他玩家的保护方块
  preciousstones.bypass.unbreakable:
    description: 可以破坏其他玩家的不可破坏方块
  preciousstones.bypass.unprotectable:
    description: 可以保护不受保护的块
  preciousstones.bypass.snitch:
    description: 不会出现任何报告列表
  preciousstones.bypass.damage:
    description: 不会出现任何报告列表
  preciousstones.bypass.setradius:
    description: 可以设置比限制更大的半径
  preciousstones.bypass.no-allowing:
    description: 可以被添加到允许列表
  preciousstones.bypass.mine:
    description: 不触发地雷领域
  preciousstones.bypass.lightning:
    description: 不触发雷击领域
  preciousstones.bypass.limits:
    description: 不受限制
  preciousstones.bypass.cuboid:
    description: 不受区域的大小限制
  preciousstones.bypass.interval:
    description: 不受最小间隔配置限制
  preciousstones.bypass.teleport:
    description: 不受传送方块影响
  preciousstones.bypass.world:
    description: 不受世界限制影响
  preciousstones.bypass.allowed-only-inside:
    description: 不受内部限制影响
  preciousstones.bypass.allowed-only-outside:
    description: 不受外部限制影响
  preciousstones.bypass.on-disabled:
    description: 不受已禁用标志影响
  preciousstones.bypass.entryalert:
    description: 不触发进入警报消息
  preciousstones.bypass.teleport:
    description: 不受传送标志影响
  preciousstones.bypass.toggle:
    description: 可以切换不受影响的模式
  preciousstones.bypass.commandblacklist:
    description: 可以不受指令黑名单的影响
  preciousstones.bypass.item-frame-take:
    description: 可以不受禁止拿走物品展示柜效果的影响
  preciousstones.bypass.entity-interact:
    description: 可以不受实体互动保护影响
  preciousstones.alert.notify.place:
    description: 可以获取方块放置通知
  preciousstones.alert.notify.destroy:
    description: 可以获取方块摧毁通知
  preciousstones.alert.notify.bypass-place:
    description: 可以获取方块的强制放置通知
  preciousstones.alert.notify.bypass-destroy:
    description: 可以获取方块的强制破坏通知
  preciousstones.alert.warn.entry:
    description: 可以获取闯入警告
  preciousstones.alert.warn.fire:
    description: 可以获取火灾警告
  preciousstones.alert.warn.pvp:
    description: 可以获取PVP警告
  preciousstones.alert.warn.use:
    description: 可以获取物品使用警告
  preciousstones.alert.warn.place:
    description: 可以获取方块放置警告
  preciousstones.alert.warn.destroy:
    description: 可以获取方块破坏警告
  preciousstones.alert.warn.noplace:
    description: 可以获取放置空间不足的警告
  preciousstones.alert.warn.destroyarea:
    description: 可以获取警报范围破坏警告
  preciousstones.alert.warn.conflict:
    description: 可以获取放置冲突警告
  preciousstones.alert.warn.unprotectable:
    description: 可以获取不受保护的相关警告
  preciousstones.admin.disableall:
    description: 可以禁用所有的标志
  preciousstones.admin.enableall:
    description: 可以启用所有的标志
  preciousstones.admin.superduperpickaxe:
    description: 能使用 superduperpickaxe
  preciousstones.admin.mark:
    description: 能使用 /ps mark (标记任何人的领域)
  preciousstones.admin.visualize:
    description: 能使用 /ps visualize (可以查看所有人的领域)
  preciousstones.admin.allowed:
    description: 能允许玩家在任何人的领域中
  preciousstones.admin.undo:
    description: 可以撤销任何人放置的危险方块
  preciousstones.admin.delete:
    description: 能使用 /ps delete
  preciousstones.admin.info:
    description: 能使用 /ps info
  preciousstones.admin.list:
    description: 能使用 /ps list
  preciousstones.admin.reload:
    description: 能使用 /ps reload
  preciousstones.admin.setowner:
    description: 能使用 /ps setowner
  preciousstones.admin.clean:
    description: 能使用 /ps clean
  preciousstones.admin.revert:
    description: 能使用 /ps revert
  preciousstones.admin.details:
    description: 可以用鼠标右键单击查看所有细节
  preciousstones.admin.bypass.log:
    description: 用户不会被日志记录
  preciousstones.admin.viewconflicting:
    description: 告诉你的位置冲突的守护之石的新领域
  preciousstones.admin.insert:
    description: 能使用 /ps insert
  preciousstones.admin.reset:
    description: 能使用 /ps reset
  preciousstones.admin.isadmin:
    description: 可检测管理员
  preciousstones.admin.counts:
    description: 可以统计每个玩家拥有的守护之石
  preciousstones.admin.locations:
    description: 可以统计玩家拥有的守护之石的位置
  preciousstones.admin.rent:
    description: 让管理员使用用于出租的租金管理权力
  preciousstones.override.notify:
    description: 用户将不会显示任何通知
  preciousstones.override.warn:
    description: 用户将不会显示任何警告
  preciousstones.translocation.use:
    description: 能使用转移领域
  preciousstones.translocation.delete:
    description: 可以删除易位领域
  preciousstones.translocation.remove:
    description: 可以在自己的易位领域删除特定的块
  preciousstones.translocation.import:
    description: 可以导入易位领域
  preciousstones.translocation.unlink:
    description: 可以断开链接的易位
  preciousstones.manual.bypass.potions:
    description: 可以不受药水效果影响
  preciousstones.limit1:
    description: 限制等级1
  preciousstones.limit2:
    description: 限制等级2
  preciousstones.limit3:
    description: 限制等级3
  preciousstones.limit4:
    description: 限制等级4
  preciousstones.limit5:
    description: 限制等级5
  preciousstones.limit6:
    description: 限制等级6
  preciousstones.limit7:
    description: 限制等级7
  preciousstones.limit8:
    description: 限制等级8
  preciousstones.limit9:
    description: 限制等级9
  preciousstones.limit10:
    description: 限制等级10
  preciousstones.limit11:
    description: 限制等级11
  preciousstones.limit12:
    description: 限制等级12
  preciousstones.limit13:
    description: 限制等级13
  preciousstones.limit14:
    description: 限制等级14
  preciousstones.limit15:
    description: 限制等级15
  preciousstones.benefit.*:
    default: false
    description: 能使用PreciousStones
    children:
      preciousstones.benefit.fields: true
      preciousstones.benefit.create.forcefield: true
      preciousstones.benefit.create.unbreakable: true
      preciousstones.benefit.heal: true
      preciousstones.benefit.potions: true
      preciousstones.benefit.giveair: true
      preciousstones.benefit.launch: true
      preciousstones.benefit.bounce: true
      preciousstones.benefit.setname: true
      preciousstones.benefit.setradius: true
      preciousstones.benefit.setvelocity: true
      preciousstones.benefit.mark: true
      preciousstones.benefit.visualize: true
      preciousstones.benefit.counts: true
      preciousstones.benefit.locations: true
      preciousstones.benefit.who: true
      preciousstones.benefit.onoff: true
      preciousstones.benefit.snitch: true
      preciousstones.benefit.repair: true
      preciousstones.benefit.feed: true
      preciousstones.benefit.density: true
      preciousstones.benefit.toggle: true
      preciousstones.benefit.setinterval: true
      preciousstones.benefit.disable: true
      preciousstones.benefit.enable: true
      preciousstones.benefit.change-owner: true
      preciousstones.benefit.hide: true
      preciousstones.benefit.setlimit: true
  preciousstones.whitelist.*:
    description: 可以给领域增加白名单
    default: false
    children:
      preciousstones.whitelist.allow: true
      preciousstones.whitelist.allowed: true
      preciousstones.whitelist.allowall: true
      preciousstones.whitelist.remove: true
      preciousstones.whitelist.removeall: true
  preciousstones.translocation.*:
    description: Can do translocation related things
    default: false
    children:
      preciousstones.translocation.use: true
      preciousstones.translocation.import: true
      preciousstones.translocation.delete: true
      preciousstones.translocation.remove: true
      preciousstones.translocation.unlink: true
  preciousstones.bypass.*:
    description: 巡查员权限
    default: op
    children:
      preciousstones.bypass.toggle: true
      preciousstones.bypass.purchase: true
      preciousstones.bypass.entry: true
      preciousstones.bypass.pvp: true
      preciousstones.bypass.place: true
      preciousstones.bypass.use: true
      preciousstones.bypass.destroy: true
      preciousstones.bypass.protection: true
      preciousstones.bypass.unbreakable: true
      preciousstones.bypass.unprotectable: true
      preciousstones.bypass.snitch: true
      preciousstones.bypass.mine: true
      preciousstones.bypass.lightning: true
      preciousstones.bypass.cuboid: true
      preciousstones.bypass.interval: true
      preciousstones.bypass.teleport: true
      preciousstones.bypass.limits: true
      preciousstones.bypass.world: true
      preciousstones.bypass.allowed-only-inside: true
      preciousstones.bypass.allowed-only-outside: true
      preciousstones.bypass.on-disabled: true
      preciousstones.bypass.setradius: true
      preciousstones.bypass.damage: true
      preciousstones.bypass.entryalert: true
      preciousstones.bypass.no-allowing: true
      preciousstones.bypass.hiding: true
      preciousstones.bypass.item-frame-take: true
      preciousstones.bypass.commandblacklist: true
      preciousstones.bypass.entity-interact: true
  preciousstones.alert.*:
    description: 获得在游戏中的提示，通知和警告 (巡查员)
    default: false
    children:
      preciousstones.alert.notify.place: true
      preciousstones.alert.notify.destroy: true
      preciousstones.alert.notify.bypass-place: true
      preciousstones.alert.notify.bypass-destroy: true
      preciousstones.alert.warn.entry: true
      preciousstones.alert.warn.fire: true
      preciousstones.alert.warn.pvp: true
      preciousstones.alert.warn.use: true
      preciousstones.alert.warn.place: true
      preciousstones.alert.warn.destroy: true
      preciousstones.alert.warn.noplace: true
      preciousstones.alert.warn.destroyarea: true
      preciousstones.alert.warn.conflict: true
      preciousstones.alert.warn.unprotectable: true
  preciousstones.admin.*:
    description: 管理员权限
    default: op
    children:
      preciousstones.admin.mark: true
      preciousstones.admin.visualize: true
      preciousstones.admin.allowed: true
      preciousstones.admin.undo: true
      preciousstones.admin.delete: true
      preciousstones.admin.info: true
      preciousstones.admin.list: true
      preciousstones.admin.reload: true
      preciousstones.admin.setowner: true
      preciousstones.admin.clean: true
      preciousstones.admin.revert: true
      preciousstones.admin.details: true
      preciousstones.admin.bypass.log: true
      preciousstones.admin.viewconflicting: true
      preciousstones.admin.isadmin: true
      preciousstones.admin.counts: true
      preciousstones.admin.locations: true
      preciousstones.admin.insert: true
      preciousstones.admin.superduperpickaxe: true
      preciousstones.admin.enableall: true
      preciousstones.admin.disableall: true
      preciousstones.admin.hideall: true
      preciousstones.admin.rent: true
  preciousstones.override.*:
    description: 这些玩家将不会收到任何警告或通知
    default: false
    children:
      preciousstones.override.notify: true
      preciousstones.override.warn: true
